# Generated by Django 4.0.3 on 2022-04-02 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.EmailField(max_length=100, unique=True, verbose_name='E-mailová adresa')),
                ('organisation_name', models.CharField(max_length=100, unique=True, verbose_name='Název organizace')),
                ('contact_person', models.CharField(blank=True, max_length=50, verbose_name='Kontaktní osoba')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Adresa')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('notes', models.TextField(blank=True, verbose_name='Poznámky')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superadmin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Organizace',
                'verbose_name_plural': 'Organizace',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='static/images/items')),
            ],
            options={
                'verbose_name': 'Položka',
                'verbose_name_plural': 'Položky',
            },
        ),
        migrations.CreateModel(
            name='ItemVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('32', '32'), ('44', '44'), ('52', '52')], max_length=50, verbose_name='velikost')),
                ('fabric_design', models.CharField(choices=[('size', 'velikost'), ('fabric_design', 'vzor')], max_length=50, verbose_name='vzor')),
                ('on_stock', models.PositiveIntegerField(verbose_name='na skladě')),
                ('reserved_quantity', models.IntegerField(verbose_name='rezervované množství')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sewedonation.item', verbose_name='položka')),
            ],
            options={
                'verbose_name': 'Varianta',
                'verbose_name_plural': 'Varianty',
            },
        ),
    ]
