# Generated by Django 4.0.3 on 2022-04-03 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sewedonation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvariation',
            name='fabric_design',
            field=models.CharField(choices=[('uni', 'uni'), ('girl', 'dívčí'), ('boy', 'chlapecký')], max_length=50, verbose_name='vzor'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True, default=django.utils.timezone.now, verbose_name='vytvořena dne')),
                ('reservation_number', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='rezervační číslo')),
                ('status', models.CharField(choices=[('new', 'nová'), ('in progress', 'rozpracovaná'), ('completed', 'připravená k odeslání'), ('closed', 'uzavřená')], default='new', max_length=50)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='upravena dne')),
                ('quantity', models.IntegerField(verbose_name='počet kusů')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sewedonation.itemvariation', verbose_name='položka')),
                ('organisation_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='název organizace')),
            ],
            options={
                'verbose_name': 'Rezervace',
                'verbose_name_plural': 'Rezervace',
            },
        ),
    ]
